name: Cleanup GHCR Packages

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at 00:00 UTC
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Run container retention policy
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          cut-off: 30d
          delete_untagged: true
          keep-n-most-recent: 0
          timestamp-to-use: 'updated_at'
          dry-run: false
